# Generated by Django 3.0.6 on 2020-05-18 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_book_borrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn13',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='borrowed',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 23, 40, 47, 522478), null=True),
        ),
    ]
