# Generated by Django 3.0.6 on 2020-05-18 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200518_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn13',
        ),
        migrations.AlterField(
            model_name='borrowed',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 0, 16, 51, 663119), null=True),
        ),
        migrations.AlterField(
            model_name='borrowed',
            name='status',
            field=models.CharField(choices=[('Due', 'Due'), ('Borrowed', 'Borrowed'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
    ]
