# Generated by Django 3.0.6 on 2020-05-18 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200519_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bigImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn13',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='borrowed',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 1, 23, 26, 799987), null=True),
        ),
        migrations.AlterField(
            model_name='borrowed',
            name='status',
            field=models.CharField(choices=[('Borrowed', 'Borrowed'), ('Pending', 'Pending'), ('Due', 'Due')], max_length=200, null=True),
        ),
    ]
