# Generated by Django 3.0.6 on 2020-05-18 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200519_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.AlterField(
            model_name='borrowed',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 1, 27, 29, 878532), null=True),
        ),
        migrations.AlterField(
            model_name='borrowed',
            name='status',
            field=models.CharField(choices=[('Borrowed', 'Borrowed'), ('Due', 'Due'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
    ]
