# Generated by Django 3.0.6 on 2020-05-18 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200519_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='borrowed',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 2, 25, 7, 411177), null=True),
        ),
        migrations.AlterField(
            model_name='borrowed',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Borrowed', 'Borrowed'), ('Due', 'Due')], max_length=200, null=True),
        ),
    ]
