# Generated by Django 3.0.6 on 2020-05-19 09:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200519_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowed',
            name='bookID',
        ),
        migrations.AddField(
            model_name='borrowed',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Book'),
        ),
        migrations.AddField(
            model_name='borrowed',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.User'),
        ),
        migrations.AlterField(
            model_name='borrowed',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 14, 52, 1, 549729), null=True),
        ),
        migrations.AlterField(
            model_name='borrowed',
            name='status',
            field=models.CharField(choices=[('Due', 'Due'), ('Borrowed', 'Borrowed'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
    ]
