# Generated by Django 3.0.6 on 2020-05-19 19:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200519_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Book2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookID', models.IntegerField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(max_length=200, null=True)),
                ('bookCount', models.IntegerField(null=True)),
                ('ratingCount', models.IntegerField(null=True)),
                ('ratingAvg', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('bigImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('language', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='borrowed',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 0, 54, 25, 648302), null=True),
        ),
        migrations.AlterField(
            model_name='borrowed',
            name='status',
            field=models.CharField(choices=[('Due', 'Due'), ('Pending', 'Pending'), ('Borrowed', 'Borrowed')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='UserRating',
        ),
        migrations.AlterField(
            model_name='borrowed',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Book2'),
        ),
    ]
