# Generated by Django 3.0.6 on 2020-05-19 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200520_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowed',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 1, 34, 28, 81490), null=True),
        ),
    ]
