# Generated by Django 3.0.6 on 2020-05-19 20:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200520_0134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleAdmin',
        ),
        migrations.AlterField(
            model_name='borrowed',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Book'),
        ),
        migrations.AlterField(
            model_name='borrowed',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 1, 36, 30, 112836), null=True),
        ),
        migrations.AlterField(
            model_name='borrowed',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Borrowed', 'Borrowed'), ('Due', 'Due')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Book2',
        ),
    ]
