# Generated by Django 3.0.6 on 2020-05-20 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200520_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowed',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 12, 2, 7, 472523), null=True),
        ),
        migrations.AlterField(
            model_name='borrowed',
            name='status',
            field=models.CharField(choices=[('Borrowed', 'Borrowed'), ('Pending', 'Pending'), ('Due', 'Due')], max_length=200, null=True),
        ),
    ]
